sudo: false

language: php

php:
  - 7.2
  - 7.3
  - '7.4snapshot'
  - nightly

install:
  - travis_retry composer install --no-interaction
  - composer info -i

script:
  - ./vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml

